import { validateDiagramDefinition, type GridDiagramDefinition } from "../schema";

export const chaptersSquadsDefinition: GridDiagramDefinition = validateDiagramDefinition({
  type: "grid",
  id: "chapters-squads",
  title: "Chapters & Squads",
  theme: "pastel-retro",
  canvas: {
    width: 1200,
    height: 640,
    background: "#f5f5f5",
  },
  accreditation: {
    originator: "Henrik Kniberg & Anders Ivarsson",
    source: "Scaling Agile @ Spotify (2012)",
    note: "Adapted for Outstride OS",
  },
  cards: [
    {
      id: "squad-a",
      title: "Squad: Banking & cards",
      subtitle: "Owns the account journey\n3 eng · PM · designer · BA",
      x: 120,
      y: 90,
      width: 280,
      height: 130,
      color: "blue",
    },
    {
      id: "squad-b",
      title: "Squad: Trading",
      subtitle: "Owns the trading journey\n3 eng · PM · designer · BA",
      x: 460,
      y: 90,
      width: 280,
      height: 130,
      color: "teal",
    },
    {
      id: "squad-c",
      title: "Squad: Onboarding & growth",
      subtitle: "Owns signup to activation\n3 eng · PM · designer · BA",
      x: 800,
      y: 90,
      width: 280,
      height: 130,
      color: "purple",
    },
    {
      id: "chapter-eng",
      title: "Engineering chapter — shared standards, one craft across all squads",
      x: 120,
      y: 280,
      width: 960,
      height: 70,
      color: "orange",
    },
    {
      id: "chapter-product",
      title: "Product chapter — one product voice across all squads",
      x: 120,
      y: 380,
      width: 960,
      height: 70,
      color: "orange",
    },
    {
      id: "chapter-design",
      title: "Design chapter — one design language across all squads",
      x: 120,
      y: 480,
      width: 960,
      height: 70,
      color: "orange",
    },
  ],
}) as GridDiagramDefinition;
