import { validateDiagramDefinition, type GridDiagramDefinition } from "../schema";

const STICKY_COLOR = "yellow";

export const company7Definition: GridDiagramDefinition = validateDiagramDefinition({
  type: "grid",
  id: "company-7",
  title: "Company 7",
  theme: "pastel-retro",
  canvas: {
    width: 1180,
    height: 420,
    background: "#f5f5f5",
  },
  accreditation: {
    note: "Outstride original",
  },
  cards: [
    {
      id: "business-growth",
      title: "Business growth",
      subtitle: "6/10",
      x: 40,
      y: 40,
      width: 250,
      height: 120,
      color: STICKY_COLOR,
    },
    {
      id: "strategy",
      title: "Strategy",
      subtitle: "7/10",
      x: 320,
      y: 40,
      width: 250,
      height: 120,
      color: STICKY_COLOR,
    },
    {
      id: "fundraising-runway",
      title: "Fundraising / Runway",
      subtitle: "5/10",
      x: 600,
      y: 40,
      width: 250,
      height: 120,
      color: STICKY_COLOR,
    },
    {
      id: "culture",
      title: "Culture",
      subtitle: "8/10",
      x: 880,
      y: 40,
      width: 250,
      height: 120,
      color: STICKY_COLOR,
    },
    {
      id: "hiring-org-structure",
      title: "Hiring & Org structure",
      subtitle: "6/10",
      x: 180,
      y: 230,
      width: 250,
      height: 120,
      color: STICKY_COLOR,
    },
    {
      id: "founder-clevel-performance",
      title: "Founder / C-level performance",
      subtitle: "7/10",
      x: 460,
      y: 230,
      width: 250,
      height: 120,
      color: STICKY_COLOR,
    },
    {
      id: "management-performance",
      title: "Management's performance",
      subtitle: "6.5/10",
      x: 740,
      y: 230,
      width: 250,
      height: 120,
      color: STICKY_COLOR,
    },
  ],
}) as GridDiagramDefinition;
