import { validateDiagramDefinition, type GridDiagramDefinition } from "../schema";

const AXIS_COLOR = "#9ca3af";
const LABEL_BG = "#f5f5f5";

export const culturePerformanceGridDefinition: GridDiagramDefinition =
  validateDiagramDefinition({
    type: "grid",
    id: "culture-performance-grid",
    title: "Culture vs Performance Grid",
    theme: "pastel-retro",
    canvas: {
      width: 1200,
      height: 640,
      background: LABEL_BG,
    },
    accreditation: {
      note: "Outstride original",
    },
    cards: [
      {
        id: "axis-vertical",
        title: "",
        x: 360,
        y: 150,
        width: 2,
        height: 430,
        color: AXIS_COLOR,
      },
      {
        id: "axis-horizontal",
        title: "",
        x: 150,
        y: 365,
        width: 520,
        height: 2,
        color: AXIS_COLOR,
      },
      {
        id: "label-culture",
        title: "Culture",
        subtitle: "Low → High ↑",
        x: 280,
        y: 70,
        width: 160,
        height: 56,
        color: LABEL_BG,
      },
      {
        id: "label-culture-low",
        title: "Low",
        x: 318,
        y: 590,
        width: 70,
        height: 28,
        color: LABEL_BG,
      },
      {
        id: "label-performance",
        title: "Performance",
        subtitle: "Low → High →",
        x: 680,
        y: 340,
        width: 170,
        height: 56,
        color: LABEL_BG,
      },
      {
        id: "label-performance-low",
        title: "Low",
        x: 150,
        y: 376,
        width: 70,
        height: 28,
        color: LABEL_BG,
      },
      {
        id: "person-note",
        title: "Sales lead",
        x: 220,
        y: 300,
        width: 120,
        height: 120,
        color: "purple",
      },
      {
        id: "quadrant-top-left",
        title: "High culture\nLow performance",
        subtitle: "Invest",
        x: 125,
        y: 165,
        width: 220,
        height: 100,
        color: LABEL_BG,
      },
      {
        id: "quadrant-top-right",
        title: "High culture\nHigh performance",
        subtitle: "Scale",
        x: 380,
        y: 165,
        width: 250,
        height: 100,
        color: LABEL_BG,
      },
      {
        id: "quadrant-bottom-left",
        title: "Low culture\nLow performance",
        subtitle: "Exit",
        x: 125,
        y: 440,
        width: 220,
        height: 100,
        color: LABEL_BG,
      },
      {
        id: "quadrant-bottom-right",
        title: "Low culture\nHigh performance",
        subtitle: "Manage out",
        x: 385,
        y: 440,
        width: 245,
        height: 100,
        color: LABEL_BG,
      },
      {
        id: "grid-note",
        title: "Plot with avg culture + performance scores",
        subtitle: "Then take the matching decision card",
        x: 760,
        y: 200,
        width: 380,
        height: 90,
        color: LABEL_BG,
      },
    ],
  }) as GridDiagramDefinition;
