import { validateDiagramDefinition, type GridDiagramDefinition } from "../schema";

export const culturePerformanceGridDefinition: GridDiagramDefinition = validateDiagramDefinition({
  type: "grid",
  id: "culture-performance-grid",
  title: "Culture vs Performance Grid",
  theme: "pastel-retro",
  canvas: {
    width: 1200,
    height: 720,
    background: "#f5f5f5",
  },
  accreditation: {
    note: "Outstride original",
  },
  cards: [
    {
      id: "axis-vertical",
      title: "",
      x: 360,
      y: 140,
      width: 2,
      height: 430,
      color: "#9ca3af",
    },
    {
      id: "axis-horizontal",
      title: "",
      x: 150,
      y: 355,
      width: 520,
      height: 2,
      color: "#9ca3af",
    },
    {
      id: "label-culture",
      title: "Culture",
      x: 282,
      y: 82,
      width: 120,
      height: 48,
      color: "#f5f5f5",
    },
    {
      id: "label-performance",
      title: "Performance",
      x: 685,
      y: 334,
      width: 150,
      height: 48,
      color: "#f5f5f5",
    },
    {
      id: "person-note",
      title: "Adam",
      x: 220,
      y: 300,
      width: 120,
      height: 120,
      color: "purple",
    },
    {
      id: "quadrant-top-left",
      title: "High culture\nLower performance",
      x: 155,
      y: 160,
      width: 190,
      height: 90,
      color: "#f5f5f5",
    },
    {
      id: "quadrant-top-right",
      title: "High culture\nHigh performance",
      x: 380,
      y: 160,
      width: 250,
      height: 90,
      color: "#f5f5f5",
    },
    {
      id: "quadrant-bottom-left",
      title: "Low culture\nLow performance",
      x: 160,
      y: 430,
      width: 190,
      height: 90,
      color: "#f5f5f5",
    },
    {
      id: "quadrant-bottom-right",
      title: "High performance\nLow culture",
      x: 385,
      y: 430,
      width: 245,
      height: 90,
      color: "#f5f5f5",
    },
    {
      id: "grid-note",
      title: "Plot employee or candidate here\nusing avg culture + performance scores",
      x: 760,
      y: 200,
      width: 380,
      height: 100,
      color: "#f5f5f5",
    },
  ],
}) as GridDiagramDefinition;
