import { validateDiagramDefinition, type GridDiagramDefinition } from "../schema";

const STICKY_COLOR = "green";

export const human9MiroDefinition: GridDiagramDefinition = validateDiagramDefinition({
  type: "grid",
  id: "human-9-miro",
  title: "Human 9 (Miro style)",
  theme: "pastel-retro",
  canvas: {
    width: 1180,
    height: 560,
    background: "#f5f5f5",
  },
  accreditation: {
    note: "Outstride original",
  },
  cards: [
    {
      id: "relationships",
      title: "Relationships",
      x: 60,
      y: 40,
      width: 220,
      height: 90,
      color: STICKY_COLOR,
    },
    {
      id: "health",
      title: "Health",
      x: 340,
      y: 40,
      width: 220,
      height: 90,
      color: STICKY_COLOR,
    },
    {
      id: "lifestyle",
      title: "Lifestyle",
      x: 620,
      y: 40,
      width: 220,
      height: 90,
      color: STICKY_COLOR,
    },
    {
      id: "money",
      title: "Money",
      x: 900,
      y: 40,
      width: 220,
      height: 90,
      color: STICKY_COLOR,
    },
    {
      id: "romantic",
      title: "Romantic",
      subtitle: "9/10",
      x: 60,
      y: 170,
      width: 220,
      height: 90,
      color: STICKY_COLOR,
    },
    {
      id: "family",
      title: "Family",
      subtitle: "9/10",
      x: 60,
      y: 280,
      width: 220,
      height: 90,
      color: STICKY_COLOR,
    },
    {
      id: "friends-community",
      title: "Friends / Community",
      subtitle: "9/10",
      x: 60,
      y: 390,
      width: 220,
      height: 90,
      color: STICKY_COLOR,
    },
    {
      id: "physical",
      title: "Physical",
      subtitle: "8.5/10",
      x: 340,
      y: 170,
      width: 220,
      height: 90,
      color: STICKY_COLOR,
    },
    {
      id: "mental",
      title: "Mental",
      subtitle: "8.5/10",
      x: 340,
      y: 280,
      width: 220,
      height: 90,
      color: STICKY_COLOR,
    },
    {
      id: "work-life-balance",
      title: "Work-Life Balance",
      subtitle: "8.5/10",
      x: 620,
      y: 170,
      width: 220,
      height: 90,
      color: STICKY_COLOR,
    },
    {
      id: "travel-fun-hobbies",
      title: "Travel, Fun & Hobbies",
      subtitle: "7.5/10",
      x: 620,
      y: 280,
      width: 220,
      height: 90,
      color: STICKY_COLOR,
    },
    {
      id: "income",
      title: "Income",
      subtitle: "7/10",
      x: 900,
      y: 170,
      width: 220,
      height: 90,
      color: STICKY_COLOR,
    },
    {
      id: "wealth",
      title: "Wealth",
      subtitle: "6.5/10",
      x: 900,
      y: 280,
      width: 220,
      height: 90,
      color: STICKY_COLOR,
    },
  ],
}) as GridDiagramDefinition;
