import { validateDiagramDefinition, type GridDiagramDefinition } from "../schema";

const BACKGROUND = "#f5f5f5";

export const northStarMetricsDefinition: GridDiagramDefinition = validateDiagramDefinition({
  type: "grid",
  id: "north-star-metrics",
  title: "North Star & Health Metrics",
  theme: "pastel-retro",
  canvas: {
    width: 1180,
    height: 490,
    background: BACKGROUND,
  },
  accreditation: {
    originator: "Sean Ellis",
    source: "North Star Metric; guardrail structure via Amplitude's North Star Playbook",
    sourceUrl: "https://amplitude.com/north-star",
    note: "Adapted for Outstride OS",
  },
  rows: [
    { id: "north-star", label: "North Star Metric", y: 70 },
    { id: "health", label: "Health Metrics", y: 290 },
  ],
  cards: [
    {
      id: "label-customer-value",
      title: "Customer Value",
      x: 480,
      y: 38,
      width: 320,
      height: 4,
      color: BACKGROUND,
    },
    {
      id: "north-star-metric",
      title: "mFAU",
      subtitle: "monthly financially active users",
      x: 480,
      y: 80,
      width: 320,
      height: 110,
      color: "green",
    },
    {
      id: "label-activation",
      title: "Activation",
      x: 170,
      y: 258,
      width: 280,
      height: 4,
      color: BACKGROUND,
    },
    {
      id: "label-engagement",
      title: "Engagement",
      x: 500,
      y: 258,
      width: 280,
      height: 4,
      color: BACKGROUND,
    },
    {
      id: "label-revenue",
      title: "Revenue",
      x: 830,
      y: 258,
      width: 280,
      height: 4,
      color: BACKGROUND,
    },
    {
      id: "health-activation",
      title: "% D14 deposits",
      x: 170,
      y: 300,
      width: 280,
      height: 110,
      color: "blue",
    },
    {
      id: "health-engagement",
      title: "% users logged in",
      x: 500,
      y: 300,
      width: 280,
      height: 110,
      color: "blue",
    },
    {
      id: "health-revenue",
      title: "ARPU",
      subtitle: "healthy: > €50",
      x: 830,
      y: 300,
      width: 280,
      height: 110,
      color: "blue",
    },
    {
      id: "operating-rule",
      title: "",
      subtitle:
        "Maximise the green metric (absolute) — as long as the blue metrics stay healthy.",
      x: 190,
      y: 445,
      width: 800,
      height: 4,
      color: BACKGROUND,
    },
  ],
}) as GridDiagramDefinition;
