import { validateDiagramDefinition, type GridDiagramDefinition } from "../schema";

export const opportunityThreatMapDefinition: GridDiagramDefinition = validateDiagramDefinition({
  type: "grid",
  id: "opportunity-threat-map",
  title: "Opportunity & Threat Map",
  theme: "pastel-retro",
  canvas: {
    width: 1200,
    height: 720,
    background: "#f5f5f5",
  },
  accreditation: {
    note: "Outstride original",
  },
  cards: [
    {
      id: "axis-vertical",
      title: "",
      x: 360,
      y: 140,
      width: 2,
      height: 430,
      color: "#9ca3af",
    },
    {
      id: "axis-horizontal",
      title: "",
      x: 150,
      y: 355,
      width: 520,
      height: 2,
      color: "#9ca3af",
    },
    {
      id: "label-magnitude",
      title: "Magnitude",
      x: 282,
      y: 82,
      width: 140,
      height: 48,
      color: "#f5f5f5",
    },
    {
      id: "label-likelihood",
      title: "Likelihood",
      x: 685,
      y: 334,
      width: 140,
      height: 48,
      color: "#f5f5f5",
    },
    {
      id: "quadrant-top-left",
      title: "Big if it lands\nProbably won't",
      x: 155,
      y: 150,
      width: 190,
      height: 60,
      color: "#f5f5f5",
    },
    {
      id: "quadrant-top-right",
      title: "Act now",
      x: 440,
      y: 150,
      width: 130,
      height: 60,
      color: "#f5f5f5",
    },
    {
      id: "quadrant-bottom-left",
      title: "Ignore",
      x: 175,
      y: 500,
      width: 150,
      height: 60,
      color: "#f5f5f5",
    },
    {
      id: "quadrant-bottom-right",
      title: "Monitor",
      x: 450,
      y: 500,
      width: 150,
      height: 60,
      color: "#f5f5f5",
    },
    {
      id: "example-opportunity",
      title: "Enterprise tier",
      subtitle: "Opportunity",
      x: 385,
      y: 205,
      width: 165,
      height: 65,
      color: "green",
    },
    {
      id: "example-threat",
      title: "Key engineer leaves",
      subtitle: "Threat",
      x: 475,
      y: 278,
      width: 180,
      height: 75,
      color: "coral",
    },
    {
      id: "example-threat-2",
      title: "Competitor price cut",
      subtitle: "Threat",
      x: 430,
      y: 395,
      width: 190,
      height: 75,
      color: "coral",
    },
    {
      id: "example-opportunity-2",
      title: "New market entry",
      subtitle: "Opportunity",
      x: 180,
      y: 240,
      width: 170,
      height: 65,
      color: "green",
    },
    {
      id: "grid-note",
      title: "Score each item 1–10 for magnitude and likelihood\nOpportunities in green, threats in red\nThe top-right corner gets owners and next steps",
      x: 760,
      y: 200,
      width: 380,
      height: 130,
      color: "#f5f5f5",
    },
  ],
}) as GridDiagramDefinition;
