/**
 * Quarterly Planning Timeline — the two-week run-up to a new quarter, by swimlane.
 *
 * Transcribed from Ben's sticky-board timeline (reference cadence for a company of
 * about 40 people). t-N = working days before the new quarter starts. Colors follow
 * the operating-cadence job legend: blue = plan, indigo = collaborate,
 * coral = hold accountable, green = communicate.
 */
import { validateDiagramDefinition, type GridDiagramDefinition } from "../schema";

const CARD_WIDTH = 176;
const CARD_HEIGHT = 95;
const SLOT_X = [128, 318, 508, 698, 888, 1078];
const LANE_Y = { clevel: 100, management: 240, company: 380 };
const LINE_COLOR = "#9ca3af";
const BG = "#f5f5f5";

export const quarterlyPlanningTimelineDefinition: GridDiagramDefinition =
  validateDiagramDefinition({
    type: "grid",
    id: "quarterly-planning-timeline",
    title: "Quarterly Planning Timeline",
    theme: "pastel-retro",
    canvas: {
      width: 1510,
      height: 570,
      background: BG,
    },
    accreditation: {
      note: "Outstride original",
    },
    rows: [
      { id: "clevel", label: "C-level", y: LANE_Y.clevel - 23 },
      { id: "management", label: "Management", y: LANE_Y.management - 23 },
      { id: "company", label: "Company", y: LANE_Y.company - 23 },
    ],
    cards: [
      {
        id: "label-t14",
        title: "t-14",
        x: SLOT_X[0],
        y: 42,
        width: CARD_WIDTH,
        height: 28,
        color: BG,
      },
      {
        id: "label-t12",
        title: "t-12",
        x: SLOT_X[1],
        y: 42,
        width: CARD_WIDTH,
        height: 28,
        color: BG,
      },
      {
        id: "label-t7",
        title: "t-7",
        x: SLOT_X[2],
        y: 42,
        width: CARD_WIDTH,
        height: 28,
        color: BG,
      },
      {
        id: "label-t5",
        title: "t-5",
        x: SLOT_X[3],
        y: 42,
        width: CARD_WIDTH,
        height: 28,
        color: BG,
      },
      {
        id: "label-t4",
        title: "t-4",
        x: SLOT_X[4],
        y: 42,
        width: CARD_WIDTH,
        height: 28,
        color: BG,
      },
      {
        id: "label-t2",
        title: "t-2",
        x: SLOT_X[5],
        y: 42,
        width: CARD_WIDTH,
        height: 28,
        color: BG,
      },
      {
        id: "line-draft-to-mgmt-v",
        title: "",
        x: SLOT_X[1] + CARD_WIDTH / 2 - 1,
        y: LANE_Y.clevel + CARD_HEIGHT,
        width: 2,
        height: 92,
        color: LINE_COLOR,
      },
      {
        id: "line-draft-to-mgmt-h",
        title: "",
        x: SLOT_X[1] + CARD_WIDTH / 2 - 1,
        y: LANE_Y.management + 46,
        width: SLOT_X[2] - SLOT_X[1] - CARD_WIDTH / 2 + 1,
        height: 2,
        color: LINE_COLOR,
      },
      {
        id: "line-team-to-approve-h",
        title: "",
        x: SLOT_X[3] + CARD_WIDTH,
        y: LANE_Y.management + 46,
        width: SLOT_X[4] + CARD_WIDTH / 2 - SLOT_X[3] - CARD_WIDTH,
        height: 2,
        color: LINE_COLOR,
      },
      {
        id: "line-team-to-approve-v",
        title: "",
        x: SLOT_X[4] + CARD_WIDTH / 2 - 1,
        y: LANE_Y.clevel + CARD_HEIGHT,
        width: 2,
        height: 93,
        color: LINE_COLOR,
      },
      {
        id: "line-approve-to-comms-h",
        title: "",
        x: SLOT_X[4] + CARD_WIDTH,
        y: LANE_Y.clevel + 46,
        width: SLOT_X[5] + CARD_WIDTH / 2 - SLOT_X[4] - CARD_WIDTH,
        height: 2,
        color: LINE_COLOR,
      },
      {
        id: "line-approve-to-comms-v",
        title: "",
        x: SLOT_X[5] + CARD_WIDTH / 2 - 1,
        y: LANE_Y.clevel + 46,
        width: 2,
        height: LANE_Y.company - LANE_Y.clevel - 46,
        color: LINE_COLOR,
      },
      {
        id: "offsite",
        title: "C-level offsite\nw. coach",
        subtitle: "OKR review ·\nstrategy · SWOT",
        x: SLOT_X[0],
        y: LANE_Y.clevel,
        width: CARD_WIDTH,
        height: CARD_HEIGHT,
        color: "blue",
      },
      {
        id: "draft-okrs",
        title: "Draft company\nOKRs",
        x: SLOT_X[1],
        y: LANE_Y.clevel,
        width: CARD_WIDTH,
        height: CARD_HEIGHT,
        color: "blue",
      },
      {
        id: "mgmt-strat",
        title: "Quarterly strat\nmeetings &\nOKR review",
        x: SLOT_X[2],
        y: LANE_Y.management,
        width: CARD_WIDTH,
        height: CARD_HEIGHT,
        color: "blue",
      },
      {
        id: "team-okrs",
        title: "Team OKRs",
        x: SLOT_X[3],
        y: LANE_Y.management,
        width: CARD_WIDTH,
        height: CARD_HEIGHT,
        color: "indigo",
      },
      {
        id: "approve-okrs",
        title: "Approve company\n& team OKRs",
        x: SLOT_X[4],
        y: LANE_Y.clevel,
        width: CARD_WIDTH,
        height: CARD_HEIGHT,
        color: "coral",
      },
      {
        id: "communicate",
        title: "Communicate to\nthe company",
        subtitle: "OKR results ·\nnew OKRs",
        x: SLOT_X[5],
        y: LANE_Y.company,
        width: CARD_WIDTH,
        height: CARD_HEIGHT,
        color: "green",
      },
      {
        id: "quarter-divider",
        title: "",
        x: 1280,
        y: 40,
        width: 3,
        height: 470,
        color: LINE_COLOR,
      },
      {
        id: "label-new-quarter",
        title: "Beginning of new quarter",
        x: 1135,
        y: 6,
        width: 290,
        height: 26,
        color: BG,
      },
      {
        id: "label-every-two-weeks",
        title: "",
        subtitle: "Every 2 weeks",
        x: 1310,
        y: 128,
        width: 186,
        height: 22,
        color: BG,
      },
      {
        id: "mgmt-checkin",
        title: "Check in w.\nmanagement team",
        x: 1310,
        y: 160,
        width: 186,
        height: CARD_HEIGHT,
        color: "coral",
      },
      {
        id: "legend",
        title: "",
        subtitle:
          "t-N = working days before the new quarter starts · reference cadence for a company of ~40 people",
        x: 415,
        y: 520,
        width: 680,
        height: 36,
        color: BG,
      },
    ],
  }) as GridDiagramDefinition;
