import { validateDiagramDefinition, type GridDiagramDefinition } from "../schema";

const LINE_COLOR = "#9ca3af";
const STAKEHOLDER_COLOR = "blue";

export const stakeholderMapDefinition: GridDiagramDefinition = validateDiagramDefinition({
  type: "grid",
  id: "stakeholder-map",
  title: "Stakeholder Map",
  theme: "pastel-retro",
  canvas: {
    width: 1180,
    height: 540,
    background: "#f5f5f5",
  },
  accreditation: {
    note: "Outstride original",
  },
  cards: [
    {
      id: "line-to-cofounder",
      title: "",
      x: 320,
      y: 94,
      width: 170,
      height: 2,
      color: LINE_COLOR,
    },
    {
      id: "line-stem",
      title: "",
      x: 589,
      y: 150,
      width: 2,
      height: 50,
      color: LINE_COLOR,
    },
    {
      id: "line-spine",
      title: "",
      x: 189,
      y: 200,
      width: 812,
      height: 2,
      color: LINE_COLOR,
    },
    {
      id: "line-drop-1",
      title: "",
      x: 189,
      y: 200,
      width: 2,
      height: 40,
      color: LINE_COLOR,
    },
    {
      id: "line-drop-2",
      title: "",
      x: 459,
      y: 200,
      width: 2,
      height: 40,
      color: LINE_COLOR,
    },
    {
      id: "line-drop-3",
      title: "",
      x: 729,
      y: 200,
      width: 2,
      height: 40,
      color: LINE_COLOR,
    },
    {
      id: "line-drop-4",
      title: "",
      x: 999,
      y: 200,
      width: 2,
      height: 40,
      color: LINE_COLOR,
    },
    {
      id: "you",
      title: "You",
      x: 490,
      y: 40,
      width: 200,
      height: 110,
      color: "teal",
    },
    {
      id: "cofounder",
      title: "Cofounder",
      subtitle: "Rel 9 · Perf 7",
      x: 100,
      y: 40,
      width: 220,
      height: 110,
      color: STAKEHOLDER_COLOR,
    },
    {
      id: "report-product",
      title: "Head of Product",
      subtitle: "Rel 9 · Perf 8",
      x: 80,
      y: 240,
      width: 220,
      height: 110,
      color: STAKEHOLDER_COLOR,
    },
    {
      id: "report-sales",
      title: "Head of Sales",
      subtitle: "Rel 8 · Perf 3",
      x: 350,
      y: 240,
      width: 220,
      height: 110,
      color: STAKEHOLDER_COLOR,
    },
    {
      id: "report-ops",
      title: "Head of Ops",
      subtitle: "Rel 7.5 · Perf 6.5",
      x: 620,
      y: 240,
      width: 220,
      height: 110,
      color: STAKEHOLDER_COLOR,
    },
    {
      id: "report-eng",
      title: "Head of Engineering",
      subtitle: "Rel 8 · Perf 8",
      x: 890,
      y: 240,
      width: 220,
      height: 110,
      color: STAKEHOLDER_COLOR,
    },
    {
      id: "legend",
      title: "",
      subtitle:
        "Rel = how the relationship is working (0–10)\nPerf = your confidence in their performance (0–10)",
      x: 240,
      y: 410,
      width: 700,
      height: 80,
      color: "#f5f5f5",
    },
  ],
}) as GridDiagramDefinition;
