import { validateDiagramDefinition, type GridDiagramDefinition } from "../schema";

export const tenMinuteRetroDefinition: GridDiagramDefinition = validateDiagramDefinition({
  type: "grid",
  id: "ten-minute-retro",
  title: "The 10-Minute Retro",
  theme: "pastel-retro",
  canvas: {
    width: 1180,
    height: 560,
    background: "#f5f5f5",
  },
  accreditation: {
    note: "Outstride original — a founder-sized cut of the classic team retrospective",
  },
  rows: [
    { id: "wins", label: "Wins", y: 35 },
    { id: "lowlights", label: "Lowlights", y: 205 },
    { id: "learnings", label: "Learnings", y: 375 },
  ],
  cards: [
    {
      id: "win-1",
      title: "Started somatic therapy",
      x: 250,
      y: 40,
      width: 270,
      height: 130,
      color: "blue",
    },
    {
      id: "win-2",
      title: "Had the hard conversations",
      x: 560,
      y: 40,
      width: 270,
      height: 130,
      color: "blue",
    },
    {
      id: "win-3",
      title: "We hit the revenue milestone",
      x: 870,
      y: 40,
      width: 270,
      height: 130,
      color: "blue",
    },
    {
      id: "lowlight-1",
      title: "Sleep and training fell apart",
      x: 250,
      y: 210,
      width: 270,
      height: 130,
      color: "orange",
    },
    {
      id: "lowlight-2",
      title: "GTM + eng took a long time to perform",
      x: 560,
      y: 210,
      width: 270,
      height: 130,
      color: "orange",
    },
    {
      id: "lowlight-3",
      title: "Not enough focus time (management instead)",
      x: 870,
      y: 210,
      width: 270,
      height: 130,
      color: "orange",
    },
    {
      id: "learning-1",
      title: "Hard conversations don't fix themselves",
      x: 250,
      y: 380,
      width: 270,
      height: 130,
      color: "green",
    },
    {
      id: "learning-2",
      title: "Short-term pain beats long-term suffering — the choice is mine",
      x: 560,
      y: 380,
      width: 270,
      height: 130,
      color: "green",
    },
    {
      id: "learning-3",
      title: "Some things are harder to do than to say",
      x: 870,
      y: 380,
      width: 270,
      height: 130,
      color: "green",
    },
  ],
}) as GridDiagramDefinition;
